# Generated by Django 4.2.6 on 2025-01-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
