# Generated by Django 4.2.6 on 2025-01-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_deportament'),
        ('account', '0002_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='departament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_deportament', to='inventory.deportament'),
            preserve_default=False,
        ),
    ]
