# Generated by Django 4.2.6 on 2025-01-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_company',
            name='image',
            field=models.ImageField(blank=True, upload_to='media_user_profile_company/%d/%m/%Y'),
        ),
    ]
