# Generated by Django 4.2.6 on 2025-01-18 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_workscheclude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='departament',
        ),
    ]
