# Generated by Django 4.2.6 on 2025-01-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_delete_deportament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fat',
            new_name='fats',
        ),
    ]
