# Generated by Django 4.2.6 on 2025-01-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_fat_product_fats'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbohydrates',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
