# Generated by Django 4.2.6 on 2025-01-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_carbohydrates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='callories',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
